export const ITEM_RESET_STATE = "ITEM_RESET_STATE";
export const ITEM_CURRENT_ITEM = "ITEM_CURRENT_ITEM";

export const ITEM_REQUEST_LOADING = "ITEM_REQUEST_LOADING";
export const ITEM_REQUEST_SUCCESS = "ITEM_REQUEST_SUCCESS";
export const ITEM_REQUEST_FAILED = "ITEM_REQUEST_FAILED";

export const ITEM_CURRENT_ACTION = "ITEM_CURRENT_ACTION";
export const ITEM_RESET_ACTION = "ITEM_RESET_ACTION";
