export const SITE_DETAILS_REQUEST = "SITE_DETAILS_REQUEST";
export const SITE_DETAILS_SUCCESS = "SITE_DETAILS_SUCCESS";
export const SITE_DETAILS_FAIL = "SITE_DETAILS_FAIL";

export const SITE_UPDATE_PROFILE_REQUEST = "SITE_UPDATE_PROFILE_REQUEST";
export const SITE_UPDATE_PROFILE_SUCCESS = "SITE_UPDATE_PROFILE_SUCCESS";
export const SITE_UPDATE_PROFILE_FAIL = "SITE_UPDATE_PROFILE_FAIL";
export const SITE_UPDATE_PROFILE_RESET = "SITE_UPDATE_PROFILE_RESET";
