@hostname = localhost
@port = 5443
@host = {{hostname}}:{{port}}
@contentType = application/json
@aUserId = 60c1330f05dafc2b93baf4a3
@aSiteId = 60c1330f05dafc2b93baf4a4
@aListId = 60d0d9c097364f706238680e
@aUserToken = bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGMxMzMwZjA1ZGFmYzJiOTNiYWY0YTMiLCJpYXQiOjE2MjQ2NjAxODEsImV4cCI6MTYyNDY2Mzc4MX0.gnvSuWSPqELatQWf0_DLnivzl8s9PJ3s3qYHl5gWzl0
@bUserToken = bearer
@adminId = 60a41d2c4a25f725864629e5
@adminToken = bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGE0MWQyYzRhMjVmNzI1ODY0NjI5ZTUiLCJpYXQiOjE2MjMxMDY2MzQsImV4cCI6MTYyMzExMDIzNH0.JRBYhgSuvLjH6QLW1MQKh4FuEYv8b1AFXSSULdL1M7Q

### GET ALL USER
GET https://{{host}}/api/users
Authorization: {{adminToken}}

### USER LOGGIN
POST https://{{host}}/api/users/login
Content-Type: {{contentType}}

{
    "username": "fmpipe8",
    "password": "password"
}

### GET ALL LIST BY SITE
GET https://{{host}}/api/lists/{{aSiteId}}/site
Authorization: {{aUserToken}}

### GET LIST BY ID
GET https://{{host}}/api/lists/{{aListId}}
Authorization: {{aUserToken}}

### POST CREATE LIST
POST https://{{host}}/api/lists/{{aSiteId}}/site
Content-Type: {{contentType}}
Authorization: {{aUserToken}}

{
  "name": "List 8",
   "desc": "Description 8"
}

### DELETE LIST BY ID
DELETE https://{{host}}/api/lists/{{aListId}}
Content-Type: {{contentType}}
Authorization: {{aUserToken}}

### UPDATE LIST BY ID
PUT https://{{host}}/api/lists/{{aListId}}
Content-Type: {{contentType}}
Authorization: {{aUserToken}}

{ 
  "desc": "desc updated now"
}

### GET SITE BY ID
GET https://{{host}}/api/sites/{{aSiteId}}
Authorization: {{aUserToken}}

### PUT SITE BY ID
PUT https://{{host}}/api/sites/{{aSiteId}}
Content-Type: {{contentType}}
Authorization: {{aUserToken}}

{
  "phone": "55555555"
}

### POST SITE
POST https://{{host}}/api/sites
Content-Type: {{contentType}}
Authorization: {{aUserToken}}

{
  "owner": "{{aUserId}}",  
  "name": "New Resto",
  "siteAddress": {
    "address": "Rivadavia 12400",
    "city": "Ramos Mejia",
    "postalCode": "1704",
    "country": "Argentina"
  },
  "phone": "55555555",
  "email": "info@newresto.com.ar",
  "image": "",
  "owner": "609eeb8dcaaef933bd5c2538"
}

### GET ITEM
GET https://{{host}}/api/items
Authorization: {{adminToken}}

### POST ITEM
POST https://{{host}}/api/items
Content-Type: {{contentType}}
Authorization: {{aUserToken}}

  {
    "name": "Coffe Black",
    "description": "Coffe very strong",
    "image": "",
    "price": "2"
  }